-- H2 初回 DB 作成時に実行される DDL (env.properties の INIT=RUNSCRIPT で読込)

-- ユーザー登録機能 用 USERS テーブル
--   USER_ID は example-web の CLIENT.CLIENT_ID と同じく H2 の GENERATED BY DEFAULT を使用。
--   (Nablarch UniversalDao#insert は PK 項目を INSERT 列に含めて NULL を渡すため、
--    H2 側で GENERATED BY DEFAULT により自動採番させる。)
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID       BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    USER_NAME     VARCHAR(50) NOT NULL,
    EMAIL         VARCHAR(254) NOT NULL,
    PASSWORD      VARCHAR(100) NOT NULL,
    VERSION       BIGINT,
    REGISTERED_AT TIMESTAMP,
    PRIMARY KEY (USER_ID),
    UNIQUE (EMAIL)
);

-- 二重サブミット防止トークン用テーブル (nablarch-fw-web-doublesubmit-jdbc DbTokenSchema 規約)
--   カラム名: TOKEN, CREATED_AT (DbTokenSchema のデフォルト)
CREATE TABLE IF NOT EXISTS DOUBLE_SUBMISSION (
    TOKEN      VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL,
    PRIMARY KEY (TOKEN)
);

-- セッションストア用テーブル (nablarch-fw-web-dbstore UserSessionSchema 規約)
--   カラム名: SESSION_ID, SESSION_OBJECT, EXPIRATION_DATETIME (UserSessionSchema のデフォルト)
CREATE TABLE IF NOT EXISTS USER_SESSION (
    SESSION_ID          VARCHAR(64) NOT NULL,
    SESSION_OBJECT      BLOB,
    EXPIRATION_DATETIME TIMESTAMP,
    PRIMARY KEY (SESSION_ID)
);
